---
title: ""
subtitle: ""
output:
  html_document:
    toc: false
    toc_float: true
    toc_depth: 2
    theme: yeti
    css: styles.css  # Linking the CSS file
    includes:
      in_header: scripts.js
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

<h8>荀子曰《劝学》:</h8> 
<br>
<h5>
译文因此，不登上高山，就不知天多么高；不面临深涧，就不知道地多么厚；不懂得先代帝王的遗教，就不知道学问的博大.</h5>

<br>

<h1><strong>My north star: keep improving.</strong></h1>

<br>

<h5>Facts are constant; challenges drive growth (antifragility); perspectives evolve with new information. Therefore:</h5>

<br>

<h3>I seek and embrace challenges to push myself holistically; I have firm beliefs, but seek new perspectives and logical evidence to rapidly update these beliefs.</h3>

<br>
<h1><strong>How?</strong></h1>

<br>

<h5>Ran a business selling minecraft texture packs and creating YouTube banners for content creators when I was 10-14.</h5>

<br>

<h5>Created a university data science course for Masters students when I was 16 - which I still help run today.</h5>

<br>
<h3>More recently, my primary experiences were in growth (3x’d MRR) at an early-stage startup and investing at OIF Ventures, a A$500m venture capital fund in Sydney.</h3>

<br>
<h5>I also studied abroad at the top university in South Korea, Seoul, where I interned with the global venture capital company Antler.</h5>

<br>
<h5>And I've worked! Building machine learning models in both public sector/private insurance, notably the largest general insurer in Australia.</h5>

<br>
<h5>... plus research in [academia](https://conan1iu.github.io/academia_en.html).</h5>



<br>



<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<h6>
<center>*This site was last updated at `r format(Sys.time(), "%H:%M")` on `r format(Sys.Date(), "%d %b %Y")`*</center>
</h6>